travis:
  secure:
    BINSTAR_TOKEN: kHMsMXXxL7S0YQy9YzryethUCSMusfbzu6unWKZjs3u3+/xTGMIly6NkDkb0VxrwLO7DTcnA59Pjk4lh2QVtQxY6+Aw+1JXFULxjNR6uqs0NJZqLaipf3O9N3dNSmeDXSDKHY2OolzG3fZ926YzJR/cXDaekdb5VkNV9BkD1REDDbsrc25CA3rmCoxhgsRaO1mM6VIO2pp2ako8tu1MfdyvPqer42UDah78ytLZyTGFwsLZuUUcoS/BDLUuAOBN9zK5wn8gRxxKtugfIgtQU9t161NdxhenPDmCto8r3KaTjZNnGFXU2/sydQq4YY2U8kT/AeCpdruu6fMO2y99n9CpBlYjmwlNI9HryQNbaRePhvgRHyyi0x/W2O+LJFu8s2xDBHntqUFb3hwMb9a5jyGAun5XtHsHpphZV1EZjiSHA2rUIfr0dvIXbSLjvXmlYSDsigvEudjBhQqnRAm6iVgdK32WMjuAFwUSkUXcwOOCIjdJC6eLeAdYY1AJ0CCvLKCQFvf6lzIsHb+J8Z7bnr0/bXZcBmJUe9ICiGPX21QBZ5tglXI8+SRP1KsXqRLZZ2mLq/DnNcObQ0iTYKZ/MKtpZHCu7DpNiasSEdd22s2B/Jj2le6/q9MRmi9o6pniMa1QzwsF/pcflmaSUwZqJ4IxjO/z41zx5ICBDbjTTeXk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
